# Accuracy Score
Example can be found here <br />
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html#sklearn.metrics.accuracy_score

In [1]:
import numpy as np
from sklearn.metrics import accuracy_score

In [2]:
y_pred = [0, 2, 1, 3]
y_true = [0, 1, 2, 3]

In [3]:
accuracy_score(y_true, y_pred)

0.5

In [4]:
accuracy_score(y_true, y_pred, normalize=False)

2

# F1 Score
## A.K.A. balanced F-score or F-measure
Example can be found here <br />
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html#sklearn.metrics.f1_score

$$
\begin{equation*}
F1 = \frac{2 * recall * precision}{recall + precision}
\end{equation*}
$$

In [2]:
from sklearn.metrics import f1_score

In [3]:
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]

In [4]:
f1_score(y_true, y_pred, average='macro')

0.26666666666666666

In [5]:
f1_score(y_true, y_pred, average='micro')

0.33333333333333331

In [6]:
f1_score(y_true, y_pred, average='weighted')

0.26666666666666666

In [7]:
f1_score(y_true, y_pred, average=None)

array([ 0.8,  0. ,  0. ])

# Mean Absolute Error
Example here <br />
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_error.html#sklearn.metrics.mean_absolute_error

$$
\begin{equation*}
MAE(y, \hat{y}) = \frac{\sum_{i=0}^{n-1} |y_i - \hat{y}_i|}{n}
\end{equation*}
$$

In [6]:
from pandas import Series
from sklearn.metrics import mean_absolute_error

In [6]:
y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
mean_absolute_error(y_true, y_pred)

0.5

In [9]:
y_true = Series(y_true)
y_pred = Series(y_pred)

In [14]:
sum(abs(y_true - y_pred))/len(y_pred)

0.5

***

In [3]:
y_true = [[0.5, 1], [-1, 1], [7, -6]]
y_pred = [[0, 2], [-1, 2], [8, -5]]
mean_absolute_error(y_true, y_pred)

0.75

In [4]:
mean_absolute_error(y_true, y_pred, multioutput='raw_values')

array([ 0.5,  1. ])

In [5]:
mean_absolute_error(y_true, y_pred, multioutput=[0.3, 0.7])

0.84999999999999998

# Mean Squered Error
Mean squared is the most common metric to measure model performance. <br />
In contrast with absolute error, the residual error (the difference between predicted and the true value) is squared.

Some benefits of squaring the residual error is that error terms are positive, it emphasizes larger errors over smaller errors, and <span style="color:red">__is differentiable__</span>. <br />
Being differentiable allows us to use calculus to find minimum or maximum values, often resulting in being more computationally efficient. <br />
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html#sklearn.metrics.mean_squared_error

$$
\begin{equation*}
MSE(y, \hat{y}) = \frac{\sum_{i=0}^{n-1} (y_i - \hat{y}_i)^2}{n}
\end{equation*}
$$

In [1]:
from sklearn.metrics import mean_squared_error

In [28]:
y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
mean_squared_error(y_true, y_pred)

0.375

In [29]:
y_true = Series(y_true)
y_pred = Series(y_pred)

In [34]:
sum( (y_true - y_pred).pow(2) )/len(y_pred)

0.375

***

In [25]:
y_true = [[0.5, 1],[-1, 1],[7, -6]]
y_pred = [[0, 2],[-1, 2],[8, -5]]
mean_squared_error(y_true, y_pred)  

0.70833333333333337

In [4]:
mean_squared_error(y_true, y_pred, multioutput='raw_values')

array([ 0.41666667,  1.        ])

In [5]:
mean_squared_error(y_true, y_pred, multioutput=[0.3, 0.7])

0.82499999999999996

# R2 Score
computes the coefficient of determination of predictions for true values. This is the default scoring method for regression learners in scikit-learn. <br />
* http://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html#sklearn.metrics.r2_score
* http://scikit-learn.org/stable/modules/model_evaluation.html#r2-score

In [11]:
from sklearn.metrics import r2_score
import numpy as np

y_true = np.array([3, -0.5, 2, 7])
y_pred = np.array([2.5, 0.0, 2, 8])
r2_score(y_true, y_pred)

0.94860813704496794

$$
\begin{equation*}
R^2 = 1 - \frac{ \sum{ (y - \hat{y}})^2 }{ \sum{ (y - \bar{y})^2 }}
\end{equation*}
$$

In [22]:
def ssy(x, y):
    return 1.0*sum( (x - y)**2 )

def r_squared(x, y):
    x_ = np.array(x)
    y_ = np.array(y)
    return 1.0 - ssy(x_, y_)/ssy(x_, x_.mean())

In [23]:
r_squared(y_true, y_pred)

0.94860813704496794

In [24]:
r_squared([3, -0.5, 2, 7, 4.2], [2.5, 0.0, 2.1, 7.8, 5.3])

0.9228556485355649

# Explained Variance Score
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.explained_variance_score.html#sklearn.metrics.explained_variance_score