# Build a Perceptron

In [ ]:
# ----------
# 
# In this exercise, you will put the finishing touches on a perceptron class.
#
# Finish writing the activate() method by using np.dot to compute signal
# strength and then add in a threshold for perceptron activation.
#
# ----------
import numpy as np

class Perceptron:
    """
    This class models an artificial neuron with step activation function.
    """
    def __init__(self, weights = np.array([1]), threshold = 0):
        """
        Initialize weights and threshold based on input arguments. Note that no
        type-checking is being performed here for simplicity.
        """
        self.weights = weights
        self.threshold = threshold
    
    def activate(self,inputs):
        """
        Takes in @param inputs, a list of numbers equal to length of weights.
        @return the output of a threshold perceptron with given inputs based on
        perceptron weights and threshold.
        """ 

        # INSERT YOUR CODE HERE
        result = inputs.dot(self.weights)
        if result > self.threshold:
            result = 1
        else:
            result = 0

        # TODO: calculate the strength with which the perceptron fires

        # TODO: return 0 or 1 based on the threshold
            
        return result

def test():
    """
    A few tests to make sure that the perceptron class performs as expected.
    Nothing should show up in the output if all the assertions pass.
    """
    p1 = Perceptron(np.array([1, 2]), 0.)
    assert p1.activate(np.array([ 1,-1])) == 0 # < threshold --> 0
    assert p1.activate(np.array([-1, 1])) == 1 # > threshold --> 1
    assert p1.activate(np.array([ 2,-1])) == 0 # on threshold --> 0
    
    p2 = Perceptron(np.array([-1,3]), 1.)
    assert p2.activate(np.array([ 2,1])) == 0 # got 1?

#if __name__ == "__main__":
test()

# Perceptron Update Rule

In [ ]:
# ----------
#
# In this exercise, you will update the perceptron class so that it can update
# its weights.
#
# Finish writing the update() method so that it updates the weights according
# to the perceptron update rule. Updates should be performed online, revising
# the weights after each data point.
# 
# ----------
import numpy as np

class Perceptron:
    """
    This class models an artificial neuron with step activation function.
    """
    def __init__(self, weights = np.array([1]), threshold = 0):
        """
        Initialize weights and threshold based on input arguments. Note that no
        type-checking is being performed here for simplicity.
        """
        self.weights = weights.astype(float) 
        self.threshold = threshold

    def activate(self, values):
        """
        Takes in @param values, a list of numbers equal to length of weights.
        @return the output of a threshold perceptron with given inputs based on
        perceptron weights and threshold.
        """
        # First calculate the strength with which the perceptron fires
        strength = np.dot(values,self.weights)
        
        # Then return 0 or 1 depending on strength compared to threshold  
        return int(strength > self.threshold)

    def update(self, values, train, eta=.1):
        """
        Takes in a 2D array @param values consisting of a LIST of inputs and a
        1D array @param train, consisting of a corresponding list of expected
        outputs. Updates internal weights according to the perceptron training
        rule using these values and an optional learning rate, @param eta.
        """
        # TODO: for each data point...  
        # Para cada input:
        #   + Criar um array de 'pesos' temporário;
        #   + Para cada peso, atualizar de acordo com a regra wi + eta * (y - ÿ) * xi
        #   + No final, atualizar o peso.
        for idx, val in enumerate(values):
            #print 'weights %s' % self.weights
            #print 'idx: %d; val: %s' % (idx, val)
            #print 'y: %s; ÿ: %s\n' % (train[idx], self.activate(values[idx]))
            wt = np.copy(self.weights)
            for i, w in enumerate(self.weights):
                #print 'input %s t: %s' % (i, w)
                wt[i] = wt[i] + eta * (train[idx] - self.activate(values[idx]))*val[i]
                #self.weights += update * xi
            self.weights = wt
            #print wt
            # TODO: obtain the neuron's prediction for that point

            # TODO: update self.weights based on prediction accuracy, learning
            # rate and input value

def test():
    """
    A few tests to make sure that the perceptron class performs as expected.
    Nothing should show up in the output if all the assertions pass.
    """
    def sum_almost_equal(array1, array2, tol = 1e-6):
        return sum(abs(array1 - array2)) < tol

    p2 = Perceptron(np.array([1,2,3]),0)
    p2.update(np.array([[3,2,1],[4,0,-1]]),np.array([0,0]))
    assert sum_almost_equal(p2.weights, np.array([0.7, 1.8, 2.9]))

    p1 = Perceptron(np.array([1,1,1]),0)
    p1.update(np.array([[2,0,-3]]), np.array([1]))
    assert sum_almost_equal(p1.weights, np.array([1.2, 1, 0.7]))
    
    p3 = Perceptron(np.array([3,0,2]),0)
    p3.update(np.array([[2,-2,4],[-1,-3,2],[0,2,1]]),np.array([0,1,0]))
    assert sum_almost_equal(p3.weights, np.array([2.7, -0.3, 1.7]))

test()

# Quiz: Linear representational Power

In [ ]:
i = np.array([0,1])
l1 = np.array([3,2])
l2 = np.array([-1,4])
l3 = np.array([3,-5])
l4 = np.array([1,2,-1])

h1 = [i.dot(l1),i.dot(l2),i.dot(l3)]
h1 = np.array(h1)

print h1.dot(l4)
print i.dot(np.array([-2,15]))

# Quiz: Build the XOR Network

In this exercise, you will create a network of perceptrons that can represent the XOR function, using a network structure like those shown in the previous quizzes.

You will need to do two things:
* First, create a network of perceptrons with the correct weights
* Second, define a procedure EvalNetwork() which takes in a list of inputs and outputs the value of this network.

In [ ]:
import numpy as np

class Perceptron:
    """
    This class models an artificial neuron with step activation function.
    """
    
    def __init__(self, weights = np.array([1]), threshold = 0):
        """
        Initialize weights and threshold based on input arguments. Note that no
        type-checking is being performed here for simplicity.
        """
        self.weights = weights
        self.threshold = threshold

    def activate(self, values):
        """
        Takes in @param values, a list of numbers equal to length of weights.
        @return the output of a threshold perceptron with given inputs based on
        perceptron weights and threshold.
        """
               
        # First calculate the strength with which the perceptron fires
        strength = np.dot(values,self.weights)
        
        # Then return 0 or 1 depending on strength compared to threshold  
        return int(strength > self.threshold)

In [ ]:
pAND = Perceptron(np.array([.5, .5]), .5)

In [ ]:
pOR = Perceptron(np.array([.5, .5]), .25)
assert pOR.activate(np.array([0, 0])) == 0
assert pOR.activate(np.array([0, 1])) == 1
assert pOR.activate(np.array([1, 0])) == 1
assert pOR.activate(np.array([1, 1])) == 1

In [ ]:
input = np.array([1, 0])
input2 = np.array( [pOR.activate(input), pAND.activate(input), pOR.activate(input)] )

pOUT = Perceptron(np.array([1, -2, 1]), 1)
pOUT.activate(input2)

In [ ]:
pAND = Perceptron(np.array([.5, .5]), .5)
pOR = Perceptron(np.array([.5, .5]), .25)
pOUT = Perceptron(np.array([1, -2, 1]), 1)

# Part 1: Set up the perceptron network
Network = [
    # input layer, declare input layer perceptrons here
    [ pOR, pAND, pOR ], \
    # output node, declare output layer perceptron here
    [ pOUT ]
]

# Part 2: Define a procedure to compute the output of the network, given inputs
def EvalNetwork(inputValues, Network):
    """
    Takes in @param inputValues, a list of input values, and @param Network
    that specifies a perceptron network. @return the output of the Network for
    the given set of inputs.
    """
    # YOUR CODE HERE
    arr = []
    for layer1 in Network[0]:
        arr += [layer1.activate(inputValues)]

    # Be sure your output value is a single number
    return Network[1][0].activate(np.array(arr))

def test():
    """
    A few tests to make sure that the perceptron class performs as expected.
    """
    print "0 XOR 0 = 0?:", EvalNetwork(np.array([0,0]), Network)
    print "0 XOR 1 = 1?:", EvalNetwork(np.array([0,1]), Network)
    print "1 XOR 0 = 1?:", EvalNetwork(np.array([1,0]), Network)
    print "1 XOR 1 = 0?:", EvalNetwork(np.array([1,1]), Network)

#if __name__ == "__main__":
test()

# Quiz: Activation Function Sandbox

In [ ]:
# Python Neural Networks code originally by Szabo Roland and used with permission
#
# Modifications, comments, and exercise breakdowns by Mitchell Owen,
# (c) Udacity
#
# Retrieved originally from http://rolisz.ro/2013/04/18/neural-networks-in-python/
#
# Neural Network Sandbox
#
# Define an activation function activate(), which takes in a number and
# returns a number.
# Using test run you can see the performance of a neural network running with
# that activation function, where the inputs are 8x8 images of digits (0-9) and
# the outputs are digit predictions made by the network.
#
# ----------

import numpy as np

def tanh(x):
    return np.tanh(x)

def tanh_deriv(x):
    return 1.0 - np.tanh(x) ** 2

def logistic(x):
    return 1/(1 + np.exp(-x))

def logistic_derivative(x):
    return logistic(x) * (1-logistic(x))
    
def activate(strength):
    # Try out different functions here. Input strength will be a number, with
    # another number as output.
    return np.power(strength,2)
    
def activation_derivative(activate, strength):
    #numerically approximate
    return (activate(strength+1e-5)-activate(strength-1e-5))/(2e-5)

# Quiz: Sigmoid Programming

As with the previous perceptron exercises, you will complete some of the core methods of a sigmoid unit class.

There are two functions for you to finish:
* First, in activate(), write the sigmoid activation function.
* Second, in update(), write the gradient descent update rule. Updates should be performed online, revising the weights after each data point.


In [50]:
import numpy as np


class Sigmoid:
    """
    This class models an artificial neuron with sigmoid activation function.
    """    
    def logistic(self, x):
        return 1/(1 + np.exp(-x))

    def logistic_derivative(self, x):
        return self.logistic(x) * (1-self.logistic(x))
    
    def __init__(self, weights = np.array([1])):
        """
        Initialize weights based on input arguments. Note that no type-checking
        is being performed here for simplicity of code.
        """
        self.weights = np.ndarray.astype(np.array(weights), float)
        

        # NOTE: You do not need to worry about these two attribues for this
        # programming quiz, but these will be useful for if you want to create
        # a network out of these sigmoid units!
        self.last_input = 0 # strength of last input
        self.delta      = 0 # error signal

    def strength(self, values):
        return np.dot(values, self.weights)
    
    def activate(self, values):
        return self.logistic(self.strength(values))
    
    def cost(self, values):
        r = self.activate(values)
        return r * (1-r)
    
    def update(self, values, train, eta=.1):
        """
        Takes in a 2D array @param values consisting of a LIST of inputs and a
        1D array @param train, consisting of a corresponding list of expected
        outputs. Updates internal weights according to gradient descent using
        these values and an optional learning rate, @param eta.
        """
        # TODO: for each data point...
        for X, y_true in zip(values, train):
            # obtain the output signal for that point
            y_pred = self.activate(X)

            # YOUR CODE HERE
            wt = np.copy(self.weights)
            for idx, wi in enumerate(self.weights):
                # wt[idx] = wt[idx] + eta * (y_true - y_pred) * X[idx] * (1-y_pred) * y_pred
                # Mesma coisa que a linha de cima, função cost é a derivada do sigmoid
                wt[idx] = wt[idx] + eta * (y_true - y_pred) * X[idx] * cost(X)
            
            print self.weights, wt
            self.weights = wt

            # TODO: compute derivative of logistic function at input strength
            # Recall: d/dx logistic(x) = logistic(x)*(1-logistic(x))

            # TODO: update self.weights based on learning rate, signal accuracy,
            # function slope (derivative) and input value

def test():
    """
    A few tests to make sure that the perceptron class performs as expected.
    Nothing should show up in the output if all the assertions pass.
    """
    def sum_almost_equal(array1, array2, tol = 1e-5):
        #print array1, array2
        return sum(abs(array1 - array2)) < tol

    u1 = Sigmoid(weights=[3,-2,1])
    assert abs(u1.activate(np.array([1,2,3])) - 0.880797) < 1e-5
    
    u1.update(np.array([[1,2,3]]),np.array([0]))
    assert sum_almost_equal(u1.weights, np.array([2.990752, -2.018496, 0.972257]))

    u2 = Sigmoid(weights=[0,3,-1])
    u2.update(np.array([[-3,-1,2],[2,1,2]]),np.array([1,0]))
    assert sum_almost_equal(u2.weights, np.array([-0.030739, 2.984961, -1.027437]))

if __name__ == "__main__":
    test()

[ 3. -2.  1.] [ 2.9907522  -2.01849561  0.97225659]
[ 0.  3. -1.] [ -1.98106867e-03   2.99933964e+00  -9.98679288e-01]
[ -1.98106867e-03   2.99933964e+00  -9.98679288e-01] [-0.03073901  2.98496067 -1.02743723]
